# Copyright (c) Team CharLS.
# SPDX-License-Identifier: BSD-3-Clause

variables:
  solution: '*.sln'

jobs:
- job: 'cppWindows'
  pool:
    vmImage: windows-latest
  displayName: 'Build on Windows'

  strategy:
    matrix:
      x86-Debug:
        buildPlatform: 'Win32'
        buildConfiguration: 'Debug'
      x86-Release:
        buildPlatform: 'Win32'
        buildConfiguration: 'Release'
      x64-Debug:
        buildPlatform: 'x64'
        buildConfiguration: 'Debug'
      x64-Release:
        buildPlatform: 'x64'
        buildConfiguration: 'Release'  

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      includeNuGetOrg: true
      restoreSolution: '*.sln'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      maximumCpuCount: true
      msbuildArgs: -p:JPEGLS_WIC_CODEC_PROFILE=true -p:JPEGLS_WIC_CODEC_ALL_WARNINGS=true

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      runInParallel: true
      resultsFolder: '$(build.ArtifactStagingDirectory)/Test/Results'
      codeCoverageEnabled: true
      runSettingsFile: 'test\CodeCoverage.runsettings'

