# SPDX-FileCopyrightText: © 2024 Team CharLS
# SPDX-License-Identifier: BSD-3-Clause

# This is a configuration file for the reuse lint tool. It allows specifing license info
# for files that cannot be extended with such info.

version = 1

[[annotations]]
path = [
    "**.pgm",
    "**.ppm",
    "**.jls",
    "**.vcxproj",
    "**.filters",
    "**/packages.config",
    "spelling.dic",
    "default.ruleset",
    "jpegls-wic-codec.sln",
    "setup/global.json",
    "setup/setup.sln",
    "jpegls-wic-codec.sln.DotSettings",
    "restore-windows-photo-viewer.reg",
    "test/CodeCoverage.runsettings"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "© 2024 Team CharLS"
SPDX-License-Identifier = "BSD-3-Clause"
